# Generated by Django 3.0.4 on 2020-03-16 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
